version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - automerge
  - package-ecosystem: npm
    directory: "/hashira-web"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - automerge
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: gomod
    directory: "/hashira-web/functions"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - automerge
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - automerge
