project_name: hashira
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: hashira-cui
    main: ./cmd/hashira-cui
    binary: hashira-cui
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
  - id: hashira-web-client
    main: ./cmd/hashira-web-client
    binary: hashira-web-client
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      386: i386
      amd64: x86_64
release:
  prerelease: auto
