package daemon

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"

	"github.com/pankona/hashira/service"
)

const (
	taskBucket     = "taskBucket"
	priorityBucket = "priorityBucket"
)

var places = []service.Place{
	service.Place_BACKLOG,
	service.Place_TODO,
	service.Place_DOING,
	service.Place_DONE,
}

var lookupPlaceByName = map[string]service.Place{
	service.Place_BACKLOG.String(): service.Place_BACKLOG,
	service.Place_TODO.String():    service.Place_TODO,
	service.Place_DOING.String():   service.Place_DOING,
	service.Place_DONE.String():    service.Place_DONE,
}

// Create creates a new task
func (d *Daemon) Create(ctx context.Context, com *service.CommandCreate) (*service.ResultCreate, error) {
	t := com.Task
	buf, err := json.Marshal(t)
	if err != nil {
		return nil, errors.New("failed to create a new task: " + err.Error())
	}

	p, err := d.retrievePriority()
	if err != nil {
		return nil, err
	}

	// specify empty id.
	// expect an id is automatically generated by database itself
	id, err := d.DB.Save(taskBucket, "", buf)
	if err != nil {
		return nil, errors.New("failed to save new task on database: " + err.Error())
	}

	// put new task on first place
	p[t.Place.String()].Ids = append([]string{id}, p[t.Place.String()].Ids...)

	_, err = d.updatePriority(p)
	if err != nil {
		return nil, err
	}

	result := &service.ResultCreate{Task: t}
	return result, nil
}

// Update updates an existing task
func (d *Daemon) Update(ctx context.Context, com *service.CommandUpdate) (*service.ResultUpdate, error) {
	if com.Task == nil {
		return nil, errors.New("failed to update a task because specified task is nil")
	}

	buf, err := json.Marshal(com.Task)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal specified task: %s", err.Error())
	}

	_, err = d.DB.Save(taskBucket, com.Task.Id, buf)
	if err != nil {
		return nil, fmt.Errorf("failed to save update of task: %s", err.Error())
	}

	return &service.ResultUpdate{
		Task: com.Task,
	}, nil
}

// Delete deletes an existing task
func (d *Daemon) Delete(ctx context.Context, com *service.CommandDelete) (*service.ResultDelete, error) {
	buf, err := d.DB.Load(taskBucket, com.Id)
	if err != nil {
		return nil, err
	}

	t := &service.Task{Id: com.Id}
	err = json.Unmarshal(buf, t)
	if err != nil {
		return nil, err
	}

	t.IsDeleted = true
	buf, err = json.Marshal(t)
	if err != nil {
		return nil, err
	}

	_, err = d.DB.Save(taskBucket, com.Id, buf)
	return &service.ResultDelete{Task: t}, err
}

// Retrieve retrieves all existing tasks
func (d *Daemon) Retrieve(ctx context.Context, com *service.CommandRetrieve) (*service.ResultRetrieve, error) {
	tasks, err := d.retrieve()
	if err != nil {
		return nil, errors.New("failed to retrieve tasks: " + err.Error())
	}

	result := &service.ResultRetrieve{
		Tasks: tasks,
	}

	return result, err
}

func (d *Daemon) retrieve() (map[string]*service.Task, error) {
	tasks := make(map[string]*service.Task)

	err := d.DB.ForEach(taskBucket, func(k, v []byte) error {
		t := &service.Task{Id: string(k)}
		err := json.Unmarshal(v, t)
		if err != nil {
			return errors.New("failed to retrieve tasks: " + err.Error())
		}

		if t.IsDeleted {
			return nil
		}

		tasks[t.Id] = t
		return nil
	})
	if err != nil {
		return nil, err
	}

	return tasks, nil
}

// returns map[Place.String()][]*service.Task
func (d *Daemon) retrieveTaskMap() (map[string]map[string]*service.Task, error) {
	m := make(map[string]map[string]*service.Task)
	for _, v := range places {
		m[v.String()] = make(map[string]*service.Task)
	}

	err := d.DB.ForEach(taskBucket, func(k, v []byte) error {
		t := &service.Task{Id: string(k)}
		err := json.Unmarshal(v, t)
		if err != nil {
			return errors.New("failed to retrieve tasks: " + err.Error())
		}

		if t.IsDeleted {
			return nil
		}

		m[t.Place.String()][t.Id] = t
		return nil
	})
	if err != nil {
		return nil, err
	}

	return m, nil
}

// UpdatePriority updates priority array
func (d *Daemon) UpdatePriority(
	ctx context.Context,
	com *service.CommandUpdatePriority) (*service.ResultUpdatePriority, error) {

	p, err := d.updatePriority(com.Priorities)

	return &service.ResultUpdatePriority{Priorities: p}, err
}

func (d *Daemon) updatePriority(p map[string]*service.Priority) (map[string]*service.Priority, error) {
	buf, err := json.Marshal(p)
	if err != nil {
		return nil, errors.New("failed to marshal CommandUpdatePriority into json: " + err.Error())
	}

	_, err = d.DB.Save(priorityBucket, "priority", buf)
	if err != nil {
		return nil, errors.New("failed to save priority on database: " + err.Error())
	}

	return p, nil
}

func lookupTaskByID(tasks map[string]map[string]*service.Task, id string) *service.Task {
	for _, t := range tasks {
		if _, ok := t[id]; ok {
			return t[id]
		}
	}
	return nil
}

// RetrievePriority returns priority array
func (d *Daemon) RetrievePriority(
	ctx context.Context,
	com *service.CommandRetrievePriority) (*service.ResultRetrievePriority, error) {

	p, err := d.retrievePriority()

	return &service.ResultRetrievePriority{Priorities: p}, err
}

func (d *Daemon) retrievePriority() (map[string]*service.Priority, error) {
	priorities, err := d.retrievePriorityMap()
	if err != nil {
		return nil, err
	}

	tasks, err := d.retrieveTaskMap()
	if err != nil {
		return nil, err
	}

	for _, priority := range priorities {
		for _, id := range priority.Ids {
			if lookupTaskByID(tasks, id) == nil {
				priority.Ids, _ = remove(priority.Ids, id)
			}
		}
	}

	for k := range tasks {
		if _, ok := priorities[k]; !ok {
			priorities[k] = &service.Priority{
				Ids: make([]string, 0),
			}
		}
		ids := priorities[k].Ids

		tasks := tasks[k]

		if len(ids) == len(tasks) {
			priorities[k].Ids = ids
			continue
		}

		m := make(map[string]struct{})

		for i, id := range ids {
			if _, ok := tasks[id]; ok {
				m[ids[i]] = struct{}{}
			}
		}

		if len(ids) < len(tasks) {
			// must cover lacked IDs
			for _, v := range tasks {
				if _, ok := m[v.Id]; !ok {
					ids = append(ids, v.Id)
				}
			}
		}

		if len(ids) > len(tasks) {
			// must remove extra IDs
			for _, v := range ids {
				if _, ok := m[v]; !ok {
					ids, _ = remove(ids, v)
				}
			}
		}
	}

	return priorities, nil
}

func remove(ids []string, id string) ([]string, bool) {
	var removed bool
	ret := make([]string, len(ids))
	var index int
	for _, v := range ids {
		if v == id {
			removed = true
			continue
		}
		ret[index] = v
		index++
	}
	return ret[:index], removed
}

func (d *Daemon) retrievePriorityMap() (map[string]*service.Priority, error) {
	m := make(map[string]*service.Priority)

	buf, err := d.DB.Load(priorityBucket, "priority")
	if err != nil {
		return nil, err
	}

	err = json.Unmarshal(buf, &m)
	if err != nil {
		log.Printf("failed to unmarshal loaded data into service.Priority: %s", err.Error())
	}

	return m, nil
}
