version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pankona/hashira
    docker:
        - image: pankona/golangci:1.12
    steps:
      - checkout
      - run:
          name: dep ensure
          command: dep ensure
      - run:
          name: test
          command: make test
      - run:
          name: golangci-lint
          command: make golangci-lint
      - run:
          name: build
          command: make

workflows:
  version: 2
  build:
    jobs:
      - build
