version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pankona/hashira
    docker:
        - image: pankona/godev:latest
    environment:
        GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: test
          command: make test
      - run:
          name: lint
          command: make lint
      - run:
          name: build
          command: make

workflows:
  version: 2
  build:
    jobs:
      - build
