// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	CommandCreate
	CommandUpdate
	CommandDelete
	CommandRetrieve
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import service1 "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandCreate struct {
	Name  string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Place service1.Place `protobuf:"varint,2,opt,name=place,enum=service.Place" json:"place,omitempty"`
}

func (m *CommandCreate) Reset()                    { *m = CommandCreate{} }
func (m *CommandCreate) String() string            { return proto.CompactTextString(m) }
func (*CommandCreate) ProtoMessage()               {}
func (*CommandCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommandCreate) GetPlace() service1.Place {
	if m != nil {
		return m.Place
	}
	return service1.Place_BACKLOG
}

type CommandUpdate struct {
	Id    string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Place service1.Place `protobuf:"varint,2,opt,name=place,enum=service.Place" json:"place,omitempty"`
}

func (m *CommandUpdate) Reset()                    { *m = CommandUpdate{} }
func (m *CommandUpdate) String() string            { return proto.CompactTextString(m) }
func (*CommandUpdate) ProtoMessage()               {}
func (*CommandUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommandUpdate) GetPlace() service1.Place {
	if m != nil {
		return m.Place
	}
	return service1.Place_BACKLOG
}

type CommandDelete struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CommandDelete) Reset()                    { *m = CommandDelete{} }
func (m *CommandDelete) String() string            { return proto.CompactTextString(m) }
func (*CommandDelete) ProtoMessage()               {}
func (*CommandDelete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommandDelete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CommandRetrieve struct {
}

func (m *CommandRetrieve) Reset()                    { *m = CommandRetrieve{} }
func (m *CommandRetrieve) String() string            { return proto.CompactTextString(m) }
func (*CommandRetrieve) ProtoMessage()               {}
func (*CommandRetrieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CommandCreate)(nil), "service.CommandCreate")
	proto.RegisterType((*CommandUpdate)(nil), "service.CommandUpdate")
	proto.RegisterType((*CommandDelete)(nil), "service.CommandDelete")
	proto.RegisterType((*CommandRetrieve)(nil), "service.CommandRetrieve")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0x95, 0xe2, 0x2e, 0xc8, 0x49, 0x4c, 0x4e, 0x85, 0x88, 0x2a, 0x79, 0x72, 0xf1, 0x3a,
	0x43, 0x94, 0x39, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x2a, 0x5c, 0xac, 0x60, 0x3d, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x7c, 0x7a, 0x50, 0xa3, 0xf4, 0x02, 0x40, 0xa2, 0x41, 0x10,
	0x49, 0x25, 0x57, 0xb8, 0x51, 0xa1, 0x05, 0x29, 0x20, 0xa3, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0xa0,
	0x06, 0x31, 0x65, 0xa6, 0x10, 0x69, 0x8c, 0x3c, 0xdc, 0x18, 0x97, 0xd4, 0x9c, 0x54, 0x4c, 0x63,
	0x94, 0x04, 0xb9, 0xf8, 0xa1, 0x0a, 0x82, 0x52, 0x4b, 0x8a, 0x32, 0x53, 0xcb, 0x52, 0x93, 0xd8,
	0xc0, 0x9e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x08, 0x7b, 0x5a, 0xc2, 0xf3, 0x00, 0x00,
	0x00,
}
