// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashira.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	hashira.proto

It has these top-level messages:
	Task
	Priority
	Priorities
	CommandCreate
	CommandUpdate
	CommandDelete
	CommandRetrieve
	CommandUpdatePriority
	CommandRetrievePriority
	ResultCreate
	ResultUpdate
	ResultDelete
	ResultRetrieve
	ResultUpdatePriority
	ResultRetrievePriority
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Place int32

const (
	Place_BACKLOG Place = 0
	Place_TODO    Place = 1
	Place_DOING   Place = 2
	Place_DONE    Place = 3
)

var Place_name = map[int32]string{
	0: "BACKLOG",
	1: "TODO",
	2: "DOING",
	3: "DONE",
}
var Place_value = map[string]int32{
	"BACKLOG": 0,
	"TODO":    1,
	"DOING":   2,
	"DONE":    3,
}

func (x Place) String() string {
	return proto.EnumName(Place_name, int32(x))
}
func (Place) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Task struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Place     Place  `protobuf:"varint,3,opt,name=place,enum=service.Place" json:"place,omitempty"`
	IsDeleted bool   `protobuf:"varint,4,opt,name=isDeleted" json:"isDeleted,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetPlace() Place {
	if m != nil {
		return m.Place
	}
	return Place_BACKLOG
}

func (m *Task) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Priority struct {
	Place Place    `protobuf:"varint,1,opt,name=place,enum=service.Place" json:"place,omitempty"`
	Ids   []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (m *Priority) Reset()                    { *m = Priority{} }
func (m *Priority) String() string            { return proto.CompactTextString(m) }
func (*Priority) ProtoMessage()               {}
func (*Priority) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Priority) GetPlace() Place {
	if m != nil {
		return m.Place
	}
	return Place_BACKLOG
}

func (m *Priority) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Priorities struct {
	ByPlace map[string]*Priority `protobuf:"bytes,1,rep,name=byPlace" json:"byPlace,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Priorities) Reset()                    { *m = Priorities{} }
func (m *Priorities) String() string            { return proto.CompactTextString(m) }
func (*Priorities) ProtoMessage()               {}
func (*Priorities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Priorities) GetByPlace() map[string]*Priority {
	if m != nil {
		return m.ByPlace
	}
	return nil
}

type CommandCreate struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Place Place  `protobuf:"varint,2,opt,name=place,enum=service.Place" json:"place,omitempty"`
}

func (m *CommandCreate) Reset()                    { *m = CommandCreate{} }
func (m *CommandCreate) String() string            { return proto.CompactTextString(m) }
func (*CommandCreate) ProtoMessage()               {}
func (*CommandCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommandCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommandCreate) GetPlace() Place {
	if m != nil {
		return m.Place
	}
	return Place_BACKLOG
}

type CommandUpdate struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Place Place  `protobuf:"varint,2,opt,name=place,enum=service.Place" json:"place,omitempty"`
}

func (m *CommandUpdate) Reset()                    { *m = CommandUpdate{} }
func (m *CommandUpdate) String() string            { return proto.CompactTextString(m) }
func (*CommandUpdate) ProtoMessage()               {}
func (*CommandUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CommandUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommandUpdate) GetPlace() Place {
	if m != nil {
		return m.Place
	}
	return Place_BACKLOG
}

type CommandDelete struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CommandDelete) Reset()                    { *m = CommandDelete{} }
func (m *CommandDelete) String() string            { return proto.CompactTextString(m) }
func (*CommandDelete) ProtoMessage()               {}
func (*CommandDelete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommandDelete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CommandRetrieve struct {
}

func (m *CommandRetrieve) Reset()                    { *m = CommandRetrieve{} }
func (m *CommandRetrieve) String() string            { return proto.CompactTextString(m) }
func (*CommandRetrieve) ProtoMessage()               {}
func (*CommandRetrieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CommandUpdatePriority struct {
	Priorities *Priorities `protobuf:"bytes,1,opt,name=priorities" json:"priorities,omitempty"`
}

func (m *CommandUpdatePriority) Reset()                    { *m = CommandUpdatePriority{} }
func (m *CommandUpdatePriority) String() string            { return proto.CompactTextString(m) }
func (*CommandUpdatePriority) ProtoMessage()               {}
func (*CommandUpdatePriority) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CommandUpdatePriority) GetPriorities() *Priorities {
	if m != nil {
		return m.Priorities
	}
	return nil
}

type CommandRetrievePriority struct {
}

func (m *CommandRetrievePriority) Reset()                    { *m = CommandRetrievePriority{} }
func (m *CommandRetrievePriority) String() string            { return proto.CompactTextString(m) }
func (*CommandRetrievePriority) ProtoMessage()               {}
func (*CommandRetrievePriority) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ResultCreate struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *ResultCreate) Reset()                    { *m = ResultCreate{} }
func (m *ResultCreate) String() string            { return proto.CompactTextString(m) }
func (*ResultCreate) ProtoMessage()               {}
func (*ResultCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResultCreate) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ResultUpdate struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *ResultUpdate) Reset()                    { *m = ResultUpdate{} }
func (m *ResultUpdate) String() string            { return proto.CompactTextString(m) }
func (*ResultUpdate) ProtoMessage()               {}
func (*ResultUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResultUpdate) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ResultDelete struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *ResultDelete) Reset()                    { *m = ResultDelete{} }
func (m *ResultDelete) String() string            { return proto.CompactTextString(m) }
func (*ResultDelete) ProtoMessage()               {}
func (*ResultDelete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResultDelete) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ResultRetrieve struct {
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *ResultRetrieve) Reset()                    { *m = ResultRetrieve{} }
func (m *ResultRetrieve) String() string            { return proto.CompactTextString(m) }
func (*ResultRetrieve) ProtoMessage()               {}
func (*ResultRetrieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ResultRetrieve) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type ResultUpdatePriority struct {
	Priorities *Priorities `protobuf:"bytes,1,opt,name=priorities" json:"priorities,omitempty"`
}

func (m *ResultUpdatePriority) Reset()                    { *m = ResultUpdatePriority{} }
func (m *ResultUpdatePriority) String() string            { return proto.CompactTextString(m) }
func (*ResultUpdatePriority) ProtoMessage()               {}
func (*ResultUpdatePriority) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ResultUpdatePriority) GetPriorities() *Priorities {
	if m != nil {
		return m.Priorities
	}
	return nil
}

type ResultRetrievePriority struct {
	Priorities *Priorities `protobuf:"bytes,1,opt,name=priorities" json:"priorities,omitempty"`
}

func (m *ResultRetrievePriority) Reset()                    { *m = ResultRetrievePriority{} }
func (m *ResultRetrievePriority) String() string            { return proto.CompactTextString(m) }
func (*ResultRetrievePriority) ProtoMessage()               {}
func (*ResultRetrievePriority) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResultRetrievePriority) GetPriorities() *Priorities {
	if m != nil {
		return m.Priorities
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "service.Task")
	proto.RegisterType((*Priority)(nil), "service.Priority")
	proto.RegisterType((*Priorities)(nil), "service.Priorities")
	proto.RegisterType((*CommandCreate)(nil), "service.CommandCreate")
	proto.RegisterType((*CommandUpdate)(nil), "service.CommandUpdate")
	proto.RegisterType((*CommandDelete)(nil), "service.CommandDelete")
	proto.RegisterType((*CommandRetrieve)(nil), "service.CommandRetrieve")
	proto.RegisterType((*CommandUpdatePriority)(nil), "service.CommandUpdatePriority")
	proto.RegisterType((*CommandRetrievePriority)(nil), "service.CommandRetrievePriority")
	proto.RegisterType((*ResultCreate)(nil), "service.ResultCreate")
	proto.RegisterType((*ResultUpdate)(nil), "service.ResultUpdate")
	proto.RegisterType((*ResultDelete)(nil), "service.ResultDelete")
	proto.RegisterType((*ResultRetrieve)(nil), "service.ResultRetrieve")
	proto.RegisterType((*ResultUpdatePriority)(nil), "service.ResultUpdatePriority")
	proto.RegisterType((*ResultRetrievePriority)(nil), "service.ResultRetrievePriority")
	proto.RegisterEnum("service.Place", Place_name, Place_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hashira service

type HashiraClient interface {
	Create(ctx context.Context, in *CommandCreate, opts ...grpc.CallOption) (*ResultCreate, error)
	Update(ctx context.Context, in *CommandUpdate, opts ...grpc.CallOption) (*ResultUpdate, error)
	Delete(ctx context.Context, in *CommandDelete, opts ...grpc.CallOption) (*ResultDelete, error)
	Retrieve(ctx context.Context, in *CommandRetrieve, opts ...grpc.CallOption) (*ResultRetrieve, error)
	UpdatePriority(ctx context.Context, in *CommandUpdatePriority, opts ...grpc.CallOption) (*ResultUpdatePriority, error)
	RetrievePriority(ctx context.Context, in *CommandRetrievePriority, opts ...grpc.CallOption) (*ResultRetrievePriority, error)
}

type hashiraClient struct {
	cc *grpc.ClientConn
}

func NewHashiraClient(cc *grpc.ClientConn) HashiraClient {
	return &hashiraClient{cc}
}

func (c *hashiraClient) Create(ctx context.Context, in *CommandCreate, opts ...grpc.CallOption) (*ResultCreate, error) {
	out := new(ResultCreate)
	err := grpc.Invoke(ctx, "/service.Hashira/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) Update(ctx context.Context, in *CommandUpdate, opts ...grpc.CallOption) (*ResultUpdate, error) {
	out := new(ResultUpdate)
	err := grpc.Invoke(ctx, "/service.Hashira/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) Delete(ctx context.Context, in *CommandDelete, opts ...grpc.CallOption) (*ResultDelete, error) {
	out := new(ResultDelete)
	err := grpc.Invoke(ctx, "/service.Hashira/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) Retrieve(ctx context.Context, in *CommandRetrieve, opts ...grpc.CallOption) (*ResultRetrieve, error) {
	out := new(ResultRetrieve)
	err := grpc.Invoke(ctx, "/service.Hashira/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) UpdatePriority(ctx context.Context, in *CommandUpdatePriority, opts ...grpc.CallOption) (*ResultUpdatePriority, error) {
	out := new(ResultUpdatePriority)
	err := grpc.Invoke(ctx, "/service.Hashira/UpdatePriority", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) RetrievePriority(ctx context.Context, in *CommandRetrievePriority, opts ...grpc.CallOption) (*ResultRetrievePriority, error) {
	out := new(ResultRetrievePriority)
	err := grpc.Invoke(ctx, "/service.Hashira/RetrievePriority", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hashira service

type HashiraServer interface {
	Create(context.Context, *CommandCreate) (*ResultCreate, error)
	Update(context.Context, *CommandUpdate) (*ResultUpdate, error)
	Delete(context.Context, *CommandDelete) (*ResultDelete, error)
	Retrieve(context.Context, *CommandRetrieve) (*ResultRetrieve, error)
	UpdatePriority(context.Context, *CommandUpdatePriority) (*ResultUpdatePriority, error)
	RetrievePriority(context.Context, *CommandRetrievePriority) (*ResultRetrievePriority, error)
}

func RegisterHashiraServer(s *grpc.Server, srv HashiraServer) {
	s.RegisterService(&_Hashira_serviceDesc, srv)
}

func _Hashira_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Create(ctx, req.(*CommandCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Update(ctx, req.(*CommandUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Delete(ctx, req.(*CommandDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRetrieve)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Retrieve(ctx, req.(*CommandRetrieve))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_UpdatePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandUpdatePriority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).UpdatePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/UpdatePriority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).UpdatePriority(ctx, req.(*CommandUpdatePriority))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_RetrievePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRetrievePriority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).RetrievePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/RetrievePriority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).RetrievePriority(ctx, req.(*CommandRetrievePriority))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hashira_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Hashira",
	HandlerType: (*HashiraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Hashira_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Hashira_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Hashira_Delete_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Hashira_Retrieve_Handler,
		},
		{
			MethodName: "UpdatePriority",
			Handler:    _Hashira_UpdatePriority_Handler,
		},
		{
			MethodName: "RetrievePriority",
			Handler:    _Hashira_RetrievePriority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashira.proto",
}

func init() { proto.RegisterFile("hashira.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x86, 0x9b, 0xa4, 0x5d, 0xdb, 0xd3, 0x35, 0x64, 0x86, 0x6d, 0xa1, 0x02, 0x16, 0x0c, 0x12,
	0x11, 0x17, 0x95, 0x48, 0x85, 0x04, 0xbb, 0x41, 0xf4, 0x43, 0x63, 0xda, 0x47, 0x8a, 0x35, 0xc4,
	0x75, 0xb6, 0x58, 0x9a, 0xd5, 0x4f, 0x25, 0x59, 0xa5, 0xfc, 0x12, 0x7e, 0x02, 0x7f, 0x13, 0x25,
	0x76, 0x9c, 0x36, 0xe9, 0xa6, 0xa1, 0xdd, 0x59, 0xe7, 0xf8, 0x7d, 0x7c, 0xfa, 0xbe, 0xa7, 0x81,
	0xf6, 0xad, 0x17, 0xde, 0xb2, 0xc0, 0xeb, 0x2e, 0x83, 0x45, 0xb4, 0x40, 0xf5, 0x90, 0x06, 0x2b,
	0x76, 0x43, 0xf1, 0x1c, 0xaa, 0x57, 0x5e, 0x38, 0x41, 0x3a, 0xa8, 0xcc, 0x37, 0x15, 0x4b, 0xb1,
	0x9b, 0x44, 0x65, 0x3e, 0x42, 0x50, 0x9d, 0x7b, 0x33, 0x6a, 0xaa, 0x69, 0x25, 0x3d, 0xa3, 0xf7,
	0x50, 0x5b, 0x4e, 0xbd, 0x1b, 0x6a, 0x6a, 0x96, 0x62, 0xeb, 0x8e, 0xde, 0x15, 0x90, 0xee, 0x38,
	0xa9, 0x12, 0xde, 0x44, 0xaf, 0xa0, 0xc9, 0xc2, 0x21, 0x9d, 0xd2, 0x88, 0xfa, 0x66, 0xd5, 0x52,
	0xec, 0x06, 0xc9, 0x0b, 0xb8, 0x0f, 0x8d, 0x71, 0xc0, 0x16, 0x01, 0x8b, 0xe2, 0x9c, 0xa7, 0x3c,
	0xc4, 0x33, 0x40, 0x63, 0x7e, 0x68, 0xaa, 0x96, 0x66, 0x37, 0x49, 0x72, 0xc4, 0x7f, 0x14, 0x00,
	0x01, 0x61, 0x34, 0x44, 0xc7, 0x50, 0xbf, 0x8e, 0xc7, 0x02, 0xa4, 0xd9, 0x2d, 0xc7, 0xca, 0x41,
	0xf2, 0x56, 0xb7, 0xcf, 0xaf, 0x8c, 0xe6, 0x51, 0x10, 0x93, 0x4c, 0xd0, 0xb9, 0x80, 0xdd, 0xf5,
	0x46, 0xf2, 0xd8, 0x84, 0xc6, 0xc2, 0x87, 0xe4, 0x88, 0x3e, 0x40, 0x6d, 0xe5, 0x4d, 0xef, 0xb8,
	0x13, 0x2d, 0x67, 0xaf, 0xc8, 0x8e, 0x09, 0xef, 0x1f, 0xab, 0x5f, 0x14, 0x7c, 0x0a, 0xed, 0xc1,
	0x62, 0x36, 0xf3, 0xe6, 0xfe, 0x20, 0xa0, 0x5e, 0x44, 0xa5, 0x8d, 0xca, 0x36, 0x1b, 0xd5, 0x07,
	0x7e, 0x36, 0x1e, 0x49, 0xd4, 0xaf, 0xa5, 0x9f, 0xa0, 0x8a, 0x09, 0x3d, 0x0e, 0x73, 0x24, 0x31,
	0x3c, 0x81, 0x22, 0x06, 0xef, 0xc1, 0x33, 0x71, 0x81, 0xd0, 0x28, 0x60, 0x74, 0x45, 0xf1, 0x39,
	0xec, 0x6f, 0x3c, 0x2d, 0x03, 0xeb, 0x01, 0x2c, 0xa5, 0xa3, 0x29, 0xa3, 0xe5, 0x3c, 0xdf, 0x62,
	0x36, 0x59, 0xbb, 0x86, 0x5f, 0xc2, 0x61, 0xe1, 0x81, 0x8c, 0x87, 0x3f, 0xc1, 0x2e, 0xa1, 0xe1,
	0xdd, 0x34, 0x12, 0x6e, 0xbd, 0x85, 0x6a, 0xe4, 0x85, 0x13, 0x41, 0x6e, 0x4b, 0x72, 0xb2, 0xa1,
	0x24, 0x6d, 0xe5, 0x12, 0xe1, 0xca, 0xff, 0x48, 0x84, 0x03, 0x8f, 0x90, 0x7c, 0x06, 0x9d, 0x4b,
	0xb2, 0x91, 0xd1, 0x3b, 0xa8, 0x25, 0x9d, 0x50, 0xac, 0x58, 0x41, 0xc5, 0x7b, 0xf8, 0x0c, 0x5e,
	0xac, 0x0f, 0xf7, 0x34, 0xdf, 0x2e, 0xe0, 0x60, 0x73, 0x86, 0x27, 0xe1, 0x3e, 0xf6, 0xa0, 0x96,
	0x2e, 0x06, 0x6a, 0x41, 0xbd, 0xff, 0x7d, 0x70, 0x76, 0xee, 0x9e, 0x18, 0x15, 0xd4, 0x80, 0xea,
	0x95, 0x3b, 0x74, 0x0d, 0x05, 0x35, 0xa1, 0x36, 0x74, 0x4f, 0x2f, 0x4f, 0x0c, 0x35, 0x29, 0x0e,
	0xdd, 0xcb, 0x91, 0xa1, 0x39, 0x7f, 0x35, 0xa8, 0xff, 0xe0, 0x1f, 0x0e, 0xf4, 0x15, 0x76, 0x44,
	0x4c, 0x07, 0xf2, 0xad, 0x8d, 0x65, 0xef, 0xec, 0xcb, 0xfa, 0x7a, 0xaa, 0xb8, 0x92, 0x48, 0x45,
	0x5c, 0x25, 0x29, 0xaf, 0x97, 0xa4, 0xbc, 0xcc, 0xa5, 0x22, 0xb6, 0x92, 0x94, 0xd7, 0x4b, 0x52,
	0x5e, 0xc6, 0x15, 0xf4, 0x0d, 0x1a, 0x32, 0x3e, 0xb3, 0x28, 0xce, 0x3a, 0x9d, 0xc3, 0x82, 0x5c,
	0xfe, 0x0b, 0x2a, 0xe8, 0x27, 0xe8, 0x85, 0x20, 0xdf, 0x6c, 0x1f, 0x3f, 0xeb, 0x77, 0x5e, 0x6f,
	0xfd, 0x19, 0x72, 0xdf, 0x2b, 0xe8, 0x37, 0x18, 0xa5, 0x38, 0xad, 0xfb, 0x66, 0x93, 0xd8, 0xa3,
	0x7b, 0x66, 0xcc, 0xc1, 0xd7, 0x3b, 0xe9, 0x77, 0xbd, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x49,
	0xa5, 0x05, 0x0a, 0xe8, 0x05, 0x00, 0x00,
}
