// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashira.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Place int32

const (
	Place_BACKLOG Place = 0
	Place_TODO    Place = 1
	Place_DOING   Place = 2
	Place_DONE    Place = 3
)

var Place_name = map[int32]string{
	0: "BACKLOG",
	1: "TODO",
	2: "DOING",
	3: "DONE",
}

var Place_value = map[string]int32{
	"BACKLOG": 0,
	"TODO":    1,
	"DOING":   2,
	"DONE":    3,
}

func (x Place) String() string {
	return proto.EnumName(Place_name, int32(x))
}

func (Place) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{0}
}

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Place                Place    `protobuf:"varint,3,opt,name=place,proto3,enum=service.Place" json:"place,omitempty"`
	IsDeleted            bool     `protobuf:"varint,4,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetPlace() Place {
	if m != nil {
		return m.Place
	}
	return Place_BACKLOG
}

func (m *Task) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Priority struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Priority) Reset()         { *m = Priority{} }
func (m *Priority) String() string { return proto.CompactTextString(m) }
func (*Priority) ProtoMessage()    {}
func (*Priority) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{1}
}

func (m *Priority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Priority.Unmarshal(m, b)
}
func (m *Priority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Priority.Marshal(b, m, deterministic)
}
func (m *Priority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Priority.Merge(m, src)
}
func (m *Priority) XXX_Size() int {
	return xxx_messageInfo_Priority.Size(m)
}
func (m *Priority) XXX_DiscardUnknown() {
	xxx_messageInfo_Priority.DiscardUnknown(m)
}

var xxx_messageInfo_Priority proto.InternalMessageInfo

func (m *Priority) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type CommandCreate struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandCreate) Reset()         { *m = CommandCreate{} }
func (m *CommandCreate) String() string { return proto.CompactTextString(m) }
func (*CommandCreate) ProtoMessage()    {}
func (*CommandCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{2}
}

func (m *CommandCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandCreate.Unmarshal(m, b)
}
func (m *CommandCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandCreate.Marshal(b, m, deterministic)
}
func (m *CommandCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandCreate.Merge(m, src)
}
func (m *CommandCreate) XXX_Size() int {
	return xxx_messageInfo_CommandCreate.Size(m)
}
func (m *CommandCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandCreate.DiscardUnknown(m)
}

var xxx_messageInfo_CommandCreate proto.InternalMessageInfo

func (m *CommandCreate) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CommandUpdate struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandUpdate) Reset()         { *m = CommandUpdate{} }
func (m *CommandUpdate) String() string { return proto.CompactTextString(m) }
func (*CommandUpdate) ProtoMessage()    {}
func (*CommandUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{3}
}

func (m *CommandUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandUpdate.Unmarshal(m, b)
}
func (m *CommandUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandUpdate.Marshal(b, m, deterministic)
}
func (m *CommandUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandUpdate.Merge(m, src)
}
func (m *CommandUpdate) XXX_Size() int {
	return xxx_messageInfo_CommandUpdate.Size(m)
}
func (m *CommandUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CommandUpdate proto.InternalMessageInfo

func (m *CommandUpdate) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CommandDelete struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandDelete) Reset()         { *m = CommandDelete{} }
func (m *CommandDelete) String() string { return proto.CompactTextString(m) }
func (*CommandDelete) ProtoMessage()    {}
func (*CommandDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{4}
}

func (m *CommandDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDelete.Unmarshal(m, b)
}
func (m *CommandDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDelete.Marshal(b, m, deterministic)
}
func (m *CommandDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDelete.Merge(m, src)
}
func (m *CommandDelete) XXX_Size() int {
	return xxx_messageInfo_CommandDelete.Size(m)
}
func (m *CommandDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDelete.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDelete proto.InternalMessageInfo

func (m *CommandDelete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CommandRetrieve struct {
	ExcludeDeleted       bool     `protobuf:"varint,1,opt,name=excludeDeleted,proto3" json:"excludeDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRetrieve) Reset()         { *m = CommandRetrieve{} }
func (m *CommandRetrieve) String() string { return proto.CompactTextString(m) }
func (*CommandRetrieve) ProtoMessage()    {}
func (*CommandRetrieve) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{5}
}

func (m *CommandRetrieve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRetrieve.Unmarshal(m, b)
}
func (m *CommandRetrieve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRetrieve.Marshal(b, m, deterministic)
}
func (m *CommandRetrieve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRetrieve.Merge(m, src)
}
func (m *CommandRetrieve) XXX_Size() int {
	return xxx_messageInfo_CommandRetrieve.Size(m)
}
func (m *CommandRetrieve) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRetrieve.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRetrieve proto.InternalMessageInfo

func (m *CommandRetrieve) GetExcludeDeleted() bool {
	if m != nil {
		return m.ExcludeDeleted
	}
	return false
}

type CommandUpdatePriority struct {
	Priorities           map[string]*Priority `protobuf:"bytes,1,rep,name=priorities,proto3" json:"priorities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommandUpdatePriority) Reset()         { *m = CommandUpdatePriority{} }
func (m *CommandUpdatePriority) String() string { return proto.CompactTextString(m) }
func (*CommandUpdatePriority) ProtoMessage()    {}
func (*CommandUpdatePriority) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{6}
}

func (m *CommandUpdatePriority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandUpdatePriority.Unmarshal(m, b)
}
func (m *CommandUpdatePriority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandUpdatePriority.Marshal(b, m, deterministic)
}
func (m *CommandUpdatePriority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandUpdatePriority.Merge(m, src)
}
func (m *CommandUpdatePriority) XXX_Size() int {
	return xxx_messageInfo_CommandUpdatePriority.Size(m)
}
func (m *CommandUpdatePriority) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandUpdatePriority.DiscardUnknown(m)
}

var xxx_messageInfo_CommandUpdatePriority proto.InternalMessageInfo

func (m *CommandUpdatePriority) GetPriorities() map[string]*Priority {
	if m != nil {
		return m.Priorities
	}
	return nil
}

type CommandRetrievePriority struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRetrievePriority) Reset()         { *m = CommandRetrievePriority{} }
func (m *CommandRetrievePriority) String() string { return proto.CompactTextString(m) }
func (*CommandRetrievePriority) ProtoMessage()    {}
func (*CommandRetrievePriority) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{7}
}

func (m *CommandRetrievePriority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRetrievePriority.Unmarshal(m, b)
}
func (m *CommandRetrievePriority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRetrievePriority.Marshal(b, m, deterministic)
}
func (m *CommandRetrievePriority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRetrievePriority.Merge(m, src)
}
func (m *CommandRetrievePriority) XXX_Size() int {
	return xxx_messageInfo_CommandRetrievePriority.Size(m)
}
func (m *CommandRetrievePriority) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRetrievePriority.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRetrievePriority proto.InternalMessageInfo

type ResultCreate struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultCreate) Reset()         { *m = ResultCreate{} }
func (m *ResultCreate) String() string { return proto.CompactTextString(m) }
func (*ResultCreate) ProtoMessage()    {}
func (*ResultCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{8}
}

func (m *ResultCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCreate.Unmarshal(m, b)
}
func (m *ResultCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCreate.Marshal(b, m, deterministic)
}
func (m *ResultCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCreate.Merge(m, src)
}
func (m *ResultCreate) XXX_Size() int {
	return xxx_messageInfo_ResultCreate.Size(m)
}
func (m *ResultCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCreate proto.InternalMessageInfo

func (m *ResultCreate) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ResultUpdate struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultUpdate) Reset()         { *m = ResultUpdate{} }
func (m *ResultUpdate) String() string { return proto.CompactTextString(m) }
func (*ResultUpdate) ProtoMessage()    {}
func (*ResultUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{9}
}

func (m *ResultUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultUpdate.Unmarshal(m, b)
}
func (m *ResultUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultUpdate.Marshal(b, m, deterministic)
}
func (m *ResultUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultUpdate.Merge(m, src)
}
func (m *ResultUpdate) XXX_Size() int {
	return xxx_messageInfo_ResultUpdate.Size(m)
}
func (m *ResultUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ResultUpdate proto.InternalMessageInfo

func (m *ResultUpdate) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ResultDelete struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultDelete) Reset()         { *m = ResultDelete{} }
func (m *ResultDelete) String() string { return proto.CompactTextString(m) }
func (*ResultDelete) ProtoMessage()    {}
func (*ResultDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{10}
}

func (m *ResultDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultDelete.Unmarshal(m, b)
}
func (m *ResultDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultDelete.Marshal(b, m, deterministic)
}
func (m *ResultDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultDelete.Merge(m, src)
}
func (m *ResultDelete) XXX_Size() int {
	return xxx_messageInfo_ResultDelete.Size(m)
}
func (m *ResultDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultDelete.DiscardUnknown(m)
}

var xxx_messageInfo_ResultDelete proto.InternalMessageInfo

func (m *ResultDelete) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ResultRetrieve struct {
	Tasks                map[string]*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResultRetrieve) Reset()         { *m = ResultRetrieve{} }
func (m *ResultRetrieve) String() string { return proto.CompactTextString(m) }
func (*ResultRetrieve) ProtoMessage()    {}
func (*ResultRetrieve) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{11}
}

func (m *ResultRetrieve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultRetrieve.Unmarshal(m, b)
}
func (m *ResultRetrieve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultRetrieve.Marshal(b, m, deterministic)
}
func (m *ResultRetrieve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultRetrieve.Merge(m, src)
}
func (m *ResultRetrieve) XXX_Size() int {
	return xxx_messageInfo_ResultRetrieve.Size(m)
}
func (m *ResultRetrieve) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultRetrieve.DiscardUnknown(m)
}

var xxx_messageInfo_ResultRetrieve proto.InternalMessageInfo

func (m *ResultRetrieve) GetTasks() map[string]*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type ResultUpdatePriority struct {
	Priorities           map[string]*Priority `protobuf:"bytes,1,rep,name=priorities,proto3" json:"priorities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResultUpdatePriority) Reset()         { *m = ResultUpdatePriority{} }
func (m *ResultUpdatePriority) String() string { return proto.CompactTextString(m) }
func (*ResultUpdatePriority) ProtoMessage()    {}
func (*ResultUpdatePriority) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{12}
}

func (m *ResultUpdatePriority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultUpdatePriority.Unmarshal(m, b)
}
func (m *ResultUpdatePriority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultUpdatePriority.Marshal(b, m, deterministic)
}
func (m *ResultUpdatePriority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultUpdatePriority.Merge(m, src)
}
func (m *ResultUpdatePriority) XXX_Size() int {
	return xxx_messageInfo_ResultUpdatePriority.Size(m)
}
func (m *ResultUpdatePriority) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultUpdatePriority.DiscardUnknown(m)
}

var xxx_messageInfo_ResultUpdatePriority proto.InternalMessageInfo

func (m *ResultUpdatePriority) GetPriorities() map[string]*Priority {
	if m != nil {
		return m.Priorities
	}
	return nil
}

type ResultRetrievePriority struct {
	Priorities           map[string]*Priority `protobuf:"bytes,1,rep,name=priorities,proto3" json:"priorities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResultRetrievePriority) Reset()         { *m = ResultRetrievePriority{} }
func (m *ResultRetrievePriority) String() string { return proto.CompactTextString(m) }
func (*ResultRetrievePriority) ProtoMessage()    {}
func (*ResultRetrievePriority) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b637012f4d4feba, []int{13}
}

func (m *ResultRetrievePriority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultRetrievePriority.Unmarshal(m, b)
}
func (m *ResultRetrievePriority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultRetrievePriority.Marshal(b, m, deterministic)
}
func (m *ResultRetrievePriority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultRetrievePriority.Merge(m, src)
}
func (m *ResultRetrievePriority) XXX_Size() int {
	return xxx_messageInfo_ResultRetrievePriority.Size(m)
}
func (m *ResultRetrievePriority) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultRetrievePriority.DiscardUnknown(m)
}

var xxx_messageInfo_ResultRetrievePriority proto.InternalMessageInfo

func (m *ResultRetrievePriority) GetPriorities() map[string]*Priority {
	if m != nil {
		return m.Priorities
	}
	return nil
}

func init() {
	proto.RegisterEnum("service.Place", Place_name, Place_value)
	proto.RegisterType((*Task)(nil), "service.Task")
	proto.RegisterType((*Priority)(nil), "service.Priority")
	proto.RegisterType((*CommandCreate)(nil), "service.CommandCreate")
	proto.RegisterType((*CommandUpdate)(nil), "service.CommandUpdate")
	proto.RegisterType((*CommandDelete)(nil), "service.CommandDelete")
	proto.RegisterType((*CommandRetrieve)(nil), "service.CommandRetrieve")
	proto.RegisterType((*CommandUpdatePriority)(nil), "service.CommandUpdatePriority")
	proto.RegisterMapType((map[string]*Priority)(nil), "service.CommandUpdatePriority.PrioritiesEntry")
	proto.RegisterType((*CommandRetrievePriority)(nil), "service.CommandRetrievePriority")
	proto.RegisterType((*ResultCreate)(nil), "service.ResultCreate")
	proto.RegisterType((*ResultUpdate)(nil), "service.ResultUpdate")
	proto.RegisterType((*ResultDelete)(nil), "service.ResultDelete")
	proto.RegisterType((*ResultRetrieve)(nil), "service.ResultRetrieve")
	proto.RegisterMapType((map[string]*Task)(nil), "service.ResultRetrieve.TasksEntry")
	proto.RegisterType((*ResultUpdatePriority)(nil), "service.ResultUpdatePriority")
	proto.RegisterMapType((map[string]*Priority)(nil), "service.ResultUpdatePriority.PrioritiesEntry")
	proto.RegisterType((*ResultRetrievePriority)(nil), "service.ResultRetrievePriority")
	proto.RegisterMapType((map[string]*Priority)(nil), "service.ResultRetrievePriority.PrioritiesEntry")
}

func init() { proto.RegisterFile("hashira.proto", fileDescriptor_2b637012f4d4feba) }

var fileDescriptor_2b637012f4d4feba = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x8d, 0xfb, 0xb3, 0xb6, 0x5f, 0x69, 0x16, 0x2c, 0xd6, 0x85, 0x68, 0xb0, 0x60, 0x10, 0x54,
	0x48, 0x04, 0x91, 0xdd, 0x6c, 0xdc, 0x20, 0x68, 0xa7, 0x82, 0x80, 0xa6, 0x44, 0x43, 0x5c, 0x87,
	0xc6, 0xd2, 0xac, 0xa6, 0x3f, 0x4a, 0xd2, 0x8a, 0x3e, 0x07, 0x0f, 0xc1, 0x23, 0x20, 0xc4, 0xcb,
	0xa1, 0xc4, 0xa9, 0xdb, 0xba, 0xe9, 0xe8, 0xdd, 0xee, 0xac, 0xf3, 0xf9, 0x38, 0xe7, 0x7c, 0xdf,
	0xb1, 0x03, 0x8d, 0x6b, 0x2f, 0xba, 0x66, 0xa1, 0x67, 0x4d, 0xc3, 0x49, 0x3c, 0xc1, 0x95, 0x88,
	0x86, 0x73, 0x36, 0xa0, 0x64, 0x0c, 0xa5, 0x2b, 0x2f, 0x1a, 0x62, 0x15, 0x0a, 0xcc, 0xd7, 0x91,
	0x89, 0x5a, 0x35, 0xb7, 0xc0, 0x7c, 0x8c, 0xa1, 0x34, 0xf6, 0x46, 0x54, 0x2f, 0xa4, 0x48, 0xba,
	0xc6, 0x4f, 0xa0, 0x3c, 0x0d, 0xbc, 0x01, 0xd5, 0x8b, 0x26, 0x6a, 0xa9, 0xb6, 0x6a, 0x65, 0x87,
	0x58, 0xfd, 0x04, 0x75, 0x79, 0x11, 0x9f, 0x40, 0x8d, 0x45, 0x1d, 0x1a, 0xd0, 0x98, 0xfa, 0x7a,
	0xc9, 0x44, 0xad, 0xaa, 0xbb, 0x02, 0xc8, 0x09, 0x54, 0xfb, 0x21, 0x9b, 0x84, 0x2c, 0x5e, 0x60,
	0x0d, 0x8a, 0xcc, 0x8f, 0x74, 0x64, 0x16, 0x5b, 0x35, 0x37, 0x59, 0x12, 0x1b, 0x1a, 0xed, 0xc9,
	0x68, 0xe4, 0x8d, 0xfd, 0x76, 0x48, 0xbd, 0x98, 0xe2, 0x47, 0x50, 0x8a, 0xbd, 0x68, 0x98, 0x0a,
	0xab, 0xdb, 0x0d, 0xf1, 0xc5, 0x44, 0xb3, 0x9b, 0x96, 0xd6, 0x38, 0x5f, 0xa7, 0xfe, 0x9e, 0x9c,
	0x53, 0xc1, 0xe1, 0xba, 0x64, 0xfb, 0xe4, 0x02, 0x0e, 0xb3, 0x0d, 0x2e, 0x8d, 0x43, 0x46, 0xe7,
	0x14, 0x3f, 0x05, 0x95, 0xfe, 0x18, 0x04, 0x33, 0x9f, 0x2e, 0xcd, 0xa1, 0xd4, 0x9c, 0x84, 0x92,
	0x3f, 0x08, 0x8e, 0x36, 0x04, 0x09, 0xbf, 0x3d, 0x80, 0x29, 0x5f, 0x33, 0xca, 0x6d, 0xd7, 0x6d,
	0x4b, 0xc8, 0xcb, 0xe5, 0x58, 0x7d, 0x41, 0xb8, 0x1c, 0xc7, 0xe1, 0xc2, 0x5d, 0x3b, 0xc1, 0xe8,
	0xc3, 0xa1, 0x54, 0x4e, 0x5a, 0x3a, 0xa4, 0x8b, 0xcc, 0x48, 0xb2, 0xc4, 0xcf, 0xa0, 0x3c, 0xf7,
	0x82, 0x19, 0x9f, 0x64, 0xdd, 0xbe, 0xbb, 0x1a, 0x5a, 0xf6, 0x09, 0x97, 0xd7, 0x5f, 0x17, 0xce,
	0x11, 0xb9, 0x0f, 0xc7, 0x92, 0xed, 0xe5, 0x2e, 0xf2, 0x0a, 0xee, 0xb8, 0x34, 0x9a, 0x05, 0xf1,
	0xfe, 0x93, 0x11, 0x94, 0xfd, 0x07, 0x23, 0x28, 0xd9, 0x5c, 0xf6, 0xa0, 0xfc, 0x44, 0xa0, 0x72,
	0x8e, 0x18, 0xd5, 0x39, 0x94, 0x93, 0xd2, 0xb2, 0xc7, 0x44, 0xd0, 0x36, 0xf7, 0xa5, 0xa7, 0x64,
	0x7d, 0xe5, 0x04, 0xa3, 0x0b, 0xb0, 0x02, 0x73, 0xba, 0xf9, 0x78, 0xb3, 0x9b, 0x92, 0xa0, 0xb5,
	0x4e, 0xfe, 0x46, 0x70, 0x6f, 0xdd, 0xbc, 0x08, 0xc1, 0xe7, 0x9c, 0x10, 0xbc, 0x90, 0x04, 0xde,
	0x6a, 0x06, 0xfe, 0x22, 0x68, 0x6e, 0xf6, 0x49, 0x68, 0x77, 0x72, 0xb4, 0xbf, 0xdc, 0xd1, 0xdc,
	0xdb, 0x51, 0xff, 0xfc, 0x0c, 0xca, 0xe9, 0x6b, 0x84, 0xeb, 0x50, 0x79, 0xf7, 0xb6, 0xfd, 0xf1,
	0x93, 0xd3, 0xd5, 0x14, 0x5c, 0x85, 0xd2, 0x95, 0xd3, 0x71, 0x34, 0x84, 0x6b, 0x50, 0xee, 0x38,
	0x1f, 0x7a, 0x5d, 0xad, 0x90, 0x80, 0x1d, 0xa7, 0x77, 0xa9, 0x15, 0xed, 0x5f, 0x45, 0xa8, 0xbc,
	0xe7, 0xef, 0x23, 0xbe, 0x80, 0x83, 0x2c, 0xe1, 0x4d, 0xf9, 0x6a, 0x72, 0xdc, 0x38, 0x92, 0x1c,
	0x73, 0x98, 0x28, 0x09, 0x35, 0x4b, 0x7a, 0x33, 0xff, 0x56, 0x6f, 0x51, 0x39, 0xcc, 0xa9, 0x59,
	0xe2, 0xb7, 0xa8, 0x1c, 0xdf, 0xa2, 0x72, 0x98, 0x28, 0xf8, 0x0d, 0x54, 0x45, 0xf0, 0x75, 0x99,
	0xbc, 0xac, 0x18, 0xc7, 0x3b, 0xc6, 0x44, 0x14, 0xfc, 0x05, 0x54, 0x29, 0xa3, 0x0f, 0x6f, 0x7e,
	0x94, 0x8c, 0x07, 0x37, 0xe6, 0x95, 0x28, 0xf8, 0x1b, 0x68, 0x5b, 0xe1, 0x31, 0x77, 0x69, 0x13,
	0xc7, 0x9e, 0xfe, 0x27, 0x4a, 0x44, 0xf9, 0x7e, 0x90, 0xfe, 0xbe, 0xce, 0xfe, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x79, 0x2f, 0x51, 0x9a, 0xcf, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HashiraClient is the client API for Hashira service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HashiraClient interface {
	Create(ctx context.Context, in *CommandCreate, opts ...grpc.CallOption) (*ResultCreate, error)
	Update(ctx context.Context, in *CommandUpdate, opts ...grpc.CallOption) (*ResultUpdate, error)
	Delete(ctx context.Context, in *CommandDelete, opts ...grpc.CallOption) (*ResultDelete, error)
	Retrieve(ctx context.Context, in *CommandRetrieve, opts ...grpc.CallOption) (*ResultRetrieve, error)
	UpdatePriority(ctx context.Context, in *CommandUpdatePriority, opts ...grpc.CallOption) (*ResultUpdatePriority, error)
	RetrievePriority(ctx context.Context, in *CommandRetrievePriority, opts ...grpc.CallOption) (*ResultRetrievePriority, error)
}

type hashiraClient struct {
	cc *grpc.ClientConn
}

func NewHashiraClient(cc *grpc.ClientConn) HashiraClient {
	return &hashiraClient{cc}
}

func (c *hashiraClient) Create(ctx context.Context, in *CommandCreate, opts ...grpc.CallOption) (*ResultCreate, error) {
	out := new(ResultCreate)
	err := c.cc.Invoke(ctx, "/service.Hashira/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) Update(ctx context.Context, in *CommandUpdate, opts ...grpc.CallOption) (*ResultUpdate, error) {
	out := new(ResultUpdate)
	err := c.cc.Invoke(ctx, "/service.Hashira/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) Delete(ctx context.Context, in *CommandDelete, opts ...grpc.CallOption) (*ResultDelete, error) {
	out := new(ResultDelete)
	err := c.cc.Invoke(ctx, "/service.Hashira/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) Retrieve(ctx context.Context, in *CommandRetrieve, opts ...grpc.CallOption) (*ResultRetrieve, error) {
	out := new(ResultRetrieve)
	err := c.cc.Invoke(ctx, "/service.Hashira/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) UpdatePriority(ctx context.Context, in *CommandUpdatePriority, opts ...grpc.CallOption) (*ResultUpdatePriority, error) {
	out := new(ResultUpdatePriority)
	err := c.cc.Invoke(ctx, "/service.Hashira/UpdatePriority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashiraClient) RetrievePriority(ctx context.Context, in *CommandRetrievePriority, opts ...grpc.CallOption) (*ResultRetrievePriority, error) {
	out := new(ResultRetrievePriority)
	err := c.cc.Invoke(ctx, "/service.Hashira/RetrievePriority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashiraServer is the server API for Hashira service.
type HashiraServer interface {
	Create(context.Context, *CommandCreate) (*ResultCreate, error)
	Update(context.Context, *CommandUpdate) (*ResultUpdate, error)
	Delete(context.Context, *CommandDelete) (*ResultDelete, error)
	Retrieve(context.Context, *CommandRetrieve) (*ResultRetrieve, error)
	UpdatePriority(context.Context, *CommandUpdatePriority) (*ResultUpdatePriority, error)
	RetrievePriority(context.Context, *CommandRetrievePriority) (*ResultRetrievePriority, error)
}

// UnimplementedHashiraServer can be embedded to have forward compatible implementations.
type UnimplementedHashiraServer struct {
}

func (*UnimplementedHashiraServer) Create(ctx context.Context, req *CommandCreate) (*ResultCreate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedHashiraServer) Update(ctx context.Context, req *CommandUpdate) (*ResultUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedHashiraServer) Delete(ctx context.Context, req *CommandDelete) (*ResultDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedHashiraServer) Retrieve(ctx context.Context, req *CommandRetrieve) (*ResultRetrieve, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (*UnimplementedHashiraServer) UpdatePriority(ctx context.Context, req *CommandUpdatePriority) (*ResultUpdatePriority, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePriority not implemented")
}
func (*UnimplementedHashiraServer) RetrievePriority(ctx context.Context, req *CommandRetrievePriority) (*ResultRetrievePriority, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrievePriority not implemented")
}

func RegisterHashiraServer(s *grpc.Server, srv HashiraServer) {
	s.RegisterService(&_Hashira_serviceDesc, srv)
}

func _Hashira_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Create(ctx, req.(*CommandCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Update(ctx, req.(*CommandUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Delete(ctx, req.(*CommandDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRetrieve)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).Retrieve(ctx, req.(*CommandRetrieve))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_UpdatePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandUpdatePriority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).UpdatePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/UpdatePriority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).UpdatePriority(ctx, req.(*CommandUpdatePriority))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashira_RetrievePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRetrievePriority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashiraServer).RetrievePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hashira/RetrievePriority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashiraServer).RetrievePriority(ctx, req.(*CommandRetrievePriority))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hashira_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Hashira",
	HandlerType: (*HashiraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Hashira_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Hashira_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Hashira_Delete_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Hashira_Retrieve_Handler,
		},
		{
			MethodName: "UpdatePriority",
			Handler:    _Hashira_UpdatePriority_Handler,
		},
		{
			MethodName: "RetrievePriority",
			Handler:    _Hashira_RetrievePriority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashira.proto",
}
