// Code generated by protoc-gen-go. DO NOT EDIT.
// source: place.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	place.proto

It has these top-level messages:
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Place int32

const (
	Place_BACKLOG Place = 0
	Place_TODO    Place = 1
	Place_DOING   Place = 2
	Place_DONE    Place = 3
)

var Place_name = map[int32]string{
	0: "BACKLOG",
	1: "TODO",
	2: "DOING",
	3: "DONE",
}
var Place_value = map[string]int32{
	"BACKLOG": 0,
	"TODO":    1,
	"DOING":   2,
	"DONE":    3,
}

func (x Place) String() string {
	return proto.EnumName(Place_name, int32(x))
}
func (Place) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("service.Place", Place_name, Place_value)
}

func init() { proto.RegisterFile("place.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc8, 0x49, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0xd5, 0x32, 0xe6, 0x62, 0x0d, 0x00, 0x89, 0x0b, 0x71, 0x73, 0xb1, 0x3b, 0x39, 0x3a, 0x7b, 0xfb,
	0xf8, 0xbb, 0x0b, 0x30, 0x08, 0x71, 0x70, 0xb1, 0x84, 0xf8, 0xbb, 0xf8, 0x0b, 0x30, 0x0a, 0x71,
	0x72, 0xb1, 0xba, 0xf8, 0x7b, 0xfa, 0xb9, 0x0b, 0x30, 0x81, 0x04, 0x5d, 0xfc, 0xfd, 0x5c, 0x05,
	0x98, 0x93, 0xd8, 0xc0, 0x86, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x6f, 0x3a, 0x4c,
	0x53, 0x00, 0x00, 0x00,
}
