name: dprint
on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          # https://github.com/dprint/dprint-plugin-prettier/issues/56
          dprint-version: "0.40.2"
