name: dprint
on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          dprint-version: "0.48.0"
