name: Auto format

on:
  push:
    branches: ["**"]

permissions:
  contents: write
  actions: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.21"

      - name: Install dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Run formatters
        run: |
          PATH="$HOME/.dprint/bin:$PATH" dprint fmt
          goimports -w .

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "style: apply automatic formatting

          🤖 Auto-formatted by GitHub Actions (dprint + goimports)

          Co-Authored-By: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
