name: hashira-web-functions

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/hashira-web-functions--test.yml"
      - "hashira-web/functions/**"
  pull_request:
    paths:
      - ".github/workflows/hashira-web-functions--test.yml"
      - "hashira-web/functions/**"

defaults:
  run:
    working-directory: ./hashira-web/functions

jobs:
  functions-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "hashira-web/functions/go.mod"
          cache-dependency-path: "hashira-web/functions/go.sum"
      - run: go test ./...
