name: hashira-web

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/hashira-web--test.yml"
      - "hashira-web/**"
      - "!hashira-web/functions/**"
  pull_request:
    paths:
      - ".github/workflows/hashira-web--test.yml"
      - "hashira-web/**"
      - "!hashira-web/functions/**"

defaults:
  run:
    working-directory: ./hashira-web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: "hashira-web/.tool-versions"
          cache: "yarn"
          cache-dependency-path: "hashira-web/yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn build
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: "hashira-web/.tool-versions"
          cache: "yarn"
          cache-dependency-path: "hashira-web/yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn typecheck
